### ISSUE TITLE
Tinywan\Jwt\JwtToken::getUser() 方法返回值

### ISSUE THREAD

**Issue by ageChen** [Tinywan/webman-jwt#18]
/**
     * @desc: 获取当前用户信息
     * @return array
     * @author Tinywan(ShaoBo Wan)
     */
    public static function getUser():array
    {
        $config = self::_getConfig();
        if (is_callable($config['user_model'])) {
            return $config['user_model'](self::getCurrentId()) ?? [];
        }
        return [];
    }
Tinywan\Jwt\JwtToken::getUser() 方法返回值如果定死了array就不能在 配置文件里返回模型对象了

**Comment by Tinywan** [comment]
你想要返回一个对象？

**Comment by ageChen** [comment]
文档中不是介绍可以返回数组或对象嘛，其次我是把整个user模型对象放到request对象中，对象方便直接调用属性或方法，这个方法的返回值不局限于array就可以让配置项里的user_model配置更灵活

**Comment by Tinywan** [comment]
好的，请更新到 `v1.8.7`
