### ISSUE TITLE
关于JWT过期、续签的一些问题

### ISSUE THREAD

**Issue by getongoing** [Tinywan/webman-jwt#21]
1.【疑问】
目前是不支持自动续签吗？
设置access_exp为2小时，无论两小时内我请不请求都会到期过期，不会按照最后一次请求的时间推算最新过期时间，是没有相关的功能还是我没找到呢···

2.【BUG】
插件改动：无
插件配置：默认配置
设置refresh_exp为7天，遇到access_token过期时（确定没有超过refresh_exp设置阈值）：
请求刷新token，Authorization格式拼接为：“Bearer ”+refresh_token，直接返回“身份验证令牌无效”。
----已多次尝试登录，待access_token过期后，请求refresh_token均提示这个错误。

谢谢

**Comment by getongoing** [comment]
2解决了，1貌似是没得的 需要自己手动触发刷新

**Comment by Tinywan** [comment]
你可以提交个PR

**Comment by getongoing** [comment]
不好意思····
第一次用不是很了解，后面跟代码了解了设计原理
用着非常顺手 谢谢大佬

**Comment by Tinywan** [comment]
好的
