### ISSUE TITLE
建议增加一些新功能

### ISSUE THREAD

**Issue by lqllife** [Tinywan/webman-jwt#8]
1. 可以根据 access_token 或 用户id ，让这一 access_token 失效
2. 限制登录用户同时在线的客户端数量

:smiling_face_with_three_hearts:

**Comment by Tinywan** [comment]
欢迎提交PR

**Comment by Tinywan** [comment]
这个只要开启单点登录就支持的

![image](https://user-images.githubusercontent.com/14959876/222432512-634efd38-ee72-46f5-9e3b-acb9ca084170.png)
